<!-- Footer -->
				<footer id="footer" class="container">
					<div class="row 200%">
						<div class="12u">

							<!-- About -->
								<div id="footer-wrap">
											<section id="footer" class="footer-style-2 dfd-background-dark">
								<div class="row ">
					<div class="three columns">
				<section id="dfd_image-2" class="widget widget_dfd_image"><div class="dfd-image-widget text-center"><img src="../WeCARE.jpg" alt="" ></div></section>			</div>
					<div class="three columns">
				<section id="text-2" class="widget widget_text"><h3 class="widget-title">Contact Info</h3>			
                <div class="textwidget"><strong>FOR INSTANT BOOKINGS OR INQUIRIES</strong><br />
Phone or SMS: 0466302892<br />
Email: wecareict1@gmail.com<br /><br />
Walk in: Shop 8/974 Waterworks Road, The Gap 
<br>Street side of The Gap Village Shopping Center<br/> 
<br>Between Pizza Capers and The Lodge Coffee
Brisbane<br />(<a href="https://www.google.com.au/maps/place/WeCARE+Massage+%26+Natural+Therapy/@-27.44546,152.9510693,17z/data=!3m1!4b1!4m5!3m4!1s0x6b9156cdadcf48b7:0x72f7b1801d279b83!8m2!3d-27.44546!4d152.953258" target="_blank">Google Map</a>) <a href="https://www.massagemag.com/best-of-2016-42498/">Related Articles</a><br /><br />

<strong>BUSINESS HOURS</strong><br />
Mon – Fri: 9 am – 5.30 pm (Thur: 9am - 8pm)<br />
Sat: 9 am – 5 pm<br />
Sun: 10am - 4 pm<br /> </div>
		</section>			</div>
					<div class="three columns">
				<section id="text-3" class="widget widget_text"><h3 class="widget-title">Latest status</h3>			
                <div class="textwidget"><div style="max-width: 90%;margin: 0 auto;">
                <iframe src="https://www.facebook.com/plugins/page.php?href=https://www.facebook.com/wecaremassage/" width="280" height="250" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe></div></div>
                
                
		</section>			</div>
					<div class="three columns">
				<section id="nav_menu-2" class="widget widget_nav_menu"><h3 class="widget-title">Quick Links</h3><ul id="menu-main-menu-1" class="menu"><li id="nav-menu-item-57-5a7ab004622ea" class="mega-menu-item nav-item menu-item-depth-0 "><a href="http://www.mystylethaimassage.com.au/" class="menu-link main-menu-link item-title"><span>Home</span></a></li>
<li id="nav-menu-item-56-5a7ab004624d4" class="mega-menu-item nav-item menu-item-depth-0 "><a href="http://www.mystylethaimassage.com.au/treatment/" class="menu-link main-menu-link item-title"><span>Treatment</span></a></li>
<li id="nav-menu-item-55-5a7ab0046269c" class="mega-menu-item nav-item menu-item-depth-0 "><a href="http://www.mystylethaimassage.com.au/comments/" class="menu-link main-menu-link item-title"><span>Comments</span></a></li>
<li id="nav-menu-item-54-5a7ab0046286a" class="mega-menu-item nav-item menu-item-depth-0 current-menu-item "><a href="http://www.mystylethaimassage.com.au/contact-us/" class="menu-link main-menu-link item-title"><span>Contact Us</span></a></li>
</ul></section>			</div>
			</div>		
            <div style="margin-top:100px;">
            <h2 class="major"><span>Get in touch</span></h2>
									<ul class="contact">
										<li><a class="icon fa-facebook" href="https://www.facebook.com/wecaremassage"><span class="label">Facebook</span></a></li>
										<li><a class="icon fa-twitter" href="https://twitter.com/We_Care_Massage"><span class="label">Twitter</span></a></li>
										<li><a class="icon fa-instagram" href="https://www.instagram.com/wecaremassage/"><span class="label">Instagram</span></a></li>
										<li><a class="icon fa-dribbble" href="https://dribbble.com/We_Care_Massage"><span class="label">Dribbble</span></a></li>
									</ul>
            </div>
						</section>


						</div>
					</div>
					<div class="row 200%">
						<div class="12u">

							<!-- Contact -->
								<section>
									
								</section>

						</div>
					</div>

					<!-- Copyright -->
						<div id="copyright">
							<ul class="menu">
								<li>&copy; WeCare Massage. All rights reserved</li>
							</ul>
						</div>

				</footer>